//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionFilms.DBLib
{
    using System;
    using System.Collections.ObjectModel;
    using MVVMLib.Core;
    
    public class Film : ObservableObject
    {
        private int _Id; public int Id { get { return _Id; } set { SetProperty(nameof(Id), ref _Id, value); } }
        private int _IdGenre; public int IdGenre { get { return _IdGenre; } set { SetProperty(nameof(IdGenre), ref _IdGenre, value); } }
        private string _Name; public string Name { get { return _Name; } set { SetProperty(nameof(Name), ref _Name, value); } }
        private Nullable<System.TimeSpan> _Duration; public Nullable<System.TimeSpan> Duration { get { return _Duration; } set { SetProperty(nameof(Duration), ref _Duration, value); } }
        private Nullable<System.DateTime> _ReleaseDate; public Nullable<System.DateTime> ReleaseDate { get { return _ReleaseDate; } set { SetProperty(nameof(ReleaseDate), ref _ReleaseDate, value); } }
        private Nullable<double> _Score; public Nullable<double> Score { get { return _Score; } set { SetProperty(nameof(Score), ref _Score, value); } }
        private string _File; public string File { get { return _File; } set { SetProperty(nameof(File), ref _File, value); } }
        private string _Tag; public string Tag { get { return _Tag; } set { SetProperty(nameof(Tag), ref _Tag, value); } }
        private Nullable<bool> _Watched; public Nullable<bool> Watched { get { return _Watched; } set { SetProperty(nameof(Watched), ref _Watched, value); } }
    
        private Genre _Genre; public virtual Genre Genre { get { return _Genre; } set { SetProperty(nameof(Genre), ref _Genre, value); } }
    }
}
